#!/usr/bin/env node
'use strict';

const autogram = require('./lib/autogram');
const colors = require("colors/safe");
const prompt = require('prompt');
const ora = require('ora');
const spinner = ora();

const argv = require('yargs')
  .usage('Usage: $0 <command> [options]')
  .example(
    '$0 run -t \'#instalife #iger\' -e \'#booty #porn\' -i 10mn',
    'Run Autogram every 10 mn on posts hashtagged #instalife, #iger, ' +
    'excluding those hashtagged #booty and #porn."'
  )
  .command(
    'run', 'Launch bot to automatize likes/comments ' +
    'actions on posts of a given hashtag.'
  )
  .option('t', {
    alias: 'hashtags',
    describe: 'Will run automatized actions on posts matching ' +
    'the given list of hashtags.'
  })
  .option('e', {
    alias: 'excludes',
    describe: 'Will avoid applying actions on posts matching ' +
    'the given list of excluded hashtags.'
  })
  .option('m', {
    alias: 'maxscrolls',
    describe: 'Number of times the bot should scroll to lazily load posts ' +
    'on a given tag. The more scrolls, the more posts it will then act on, ' +
    'the longer it will take.'
   })
  .option('c', {
    alias: 'comments',
    describe: 'A list of comments to add to the default list of canned comments, ' +
    'that are randomly typed by the bot in each posts. Comments are to be separated ' +
    'by the `comment separator` (default is `, `, that is comma + space).'
  })
  .option('s', {
    alias: 'separator',
    describe: 'Comment separator character(s). Defaults to comma + space (`, `).'
  })
  .option('v', {
    alias: 'visible',
    describe: 'If set, displays the window to enable visual monitoring.'
  })
  .help('h')
  .alias('h', 'help')
  .epilog('MIT Licensed - Davy Peter Braun')
  .argv;

prompt.message = colors.cyan('  A U T O G R A M');

prompt
  .start()
  .get({
    properties: {
      username: {
        description: 'Enter you Instagram username',
        pattern: /^[a-zA-Z\s\-]+$/,
        message: 'Name must be only letters, spaces, or dashes',
        required: true
      },
      password: {
        description: 'Enter your password (input will NOT be visible)',
        hidden: true,
        required: true
      }
    }
  }, (err, result) => {
    let msg = colors.cyan('A U T O G R A M');
    msg += ' (Ctrl + C to stop)';

    spinner.color = 'blue';
    spinner.text = msg;
    spinner.start();

    autogram(
      {
        hashtags: argv.hashtags,
        excludes: argv.excludes,
        comments: argv.comments || '',
        separator: argv.separator || ', ',
        isShown: !!argv.visible || false,
        maxScrolls: (argv.maxscrolls === 0 ? 0 : (argv.maxscrolls || 50))
      },
      {
        username: result.username.trim(),
        password: result.password.trim()
      },
      {spinner, statusPrefix: msg}
    );
  });

